export const API_BASE_URL = (
  process.env.EXPO_PUBLIC_API_BASE_URL || "https://192.168.1.40:3000"
).replace(/\/+$/, "");

// CHANGE THIS TO IPV4 ADDRESS OF YOUR MACHINE IF YOU ARE TESTING ON A REAL DEVICE